[package]
name = "qinpel-wiz"
description = "QinpelWiz - Wizard thats automagic build, install and update the Qinpel platform applications and commands."
repository = "https://github.com/emuvi/qinpel-wiz/"
authors = ["Éverton M. Vieira"]
license = "LGPL-3.0-only"
version = "0.1.3"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
octocrab = "0.15"
serde = "1"
serde_json = "1"
tokio = { version = "1", features = ["full"] }
liz = "0.1.5"
